apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubernetesdeploymentdemo
  namespace: gitopsdemo
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: kubernetesdeploymentdemo
  chart: 
    spec:
      chart: ./ArcHelmGitOps/charts/kubernetesdeploymentdemo
  values:
    replicaCount: 2